---
functional:
  - Требование 1 Пользователь должен иметь возможность авторизоваться через Github
  - Требование 2 Пользователь должен иметь возможность авторизации и голосового чата через Discord
  - Требование 3 Сайт должен иметь мобильную версию
  - Требование 4 Пользователь должен иметь возможность просматривать истории батлов
  - Требование 5 Пользователь должен иметь возможность переподключиться к игре и продолжить баттл в случае, если соединение было прервано
  - Требование 6 Кнопки "signin" и "signup" в мобильной версии должны располагаться на титульной странице приложения и быть в поле видимости пользователя
  - Требование 6 Сайт должен быть доступен на различных устройствах
non-functional:
  - Требование 7 Веб-сайт должен быть разработан с учетом удобства использования
    и оптимизирован для скорости работы
  - Требование 8 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 9 Сайт должен быть протестирован на совместимость с последними
    версиями браузеров
  - Требование 10 Сайт должен быть способен обрабатывать большое количество
    трафика
implicit:
  - Требование 11 Кнопка  должна быть одинакового размера на всех
  - Требование 12 Пользователь должен иметь возможность просматривать сайт как на английском, так и на русском языке
  - Требование 13 Кнопки "signin" и "signup" в мобильной версии должны располагаться на титульной странице приложения и быть в поле видимости пользователя
  - Требование 14 Кнопка  не должна закрывать текст 
  - Требование 15 После успешного 
  - Требование 16 При нажатии на кнопку  должно отображаться
    сообщение 
