---
functional:
  - Требование 1 Сайт должен иметь мобильную версию
  - Требование 2 Пользователь должен иметь возможность авторизации через Github
  - Требование 3 Пользователь должен иметь возможность авторизации и голосового чата через Discord
  - Требование 4 Кнопки "signin" и "signup" должны располагаться на титульной странице приложения и быть в поле видимости пользователя
  - Требование 5 Сайт должен быть доступен на различных устройствах
  - Требование 6 Пользователь должен иметь возможность создать баттл
  - Требование 7 Пользователь должен иметь возможность просматривать истории батлов
  - Требование 8 Во время проведения баттла на экране пользователя должен отображаться текст задания и примеры
  - Требование 9 Во время проведения баттла пользователь должен иметь возможность писать решение задачи в редакторе приложения
  - Требование 10 Пользователь должен иметь возможность переподключиться к игре и продолжить баттл в случае, если соединение было прервано
  - Требование 11 Пользователь должен иметь возможность выбрать язык программирования в терминале баттла
  - Требование 12 Пользователь должен иметь возможность сдаться во время игры
  - Требование 13 Пользователь должен иметь возможность попросить соперника провести матч-реванш
  - Требование 14 Во время проведения баттла пользователь должен иметь возможность сбросить код в редакторе к исходному шаблону
  - Требование 15 Во время проведения баттла пользователь должен иметь возможность проверить свое решение
  - Требование 16 Пользователь должен иметь возможность видеть результат теста или ошибки компиляции после проверки
  - Требование 17 Пользователь должен иметь возможность устанавливать время проведения баттла в промежутке от 3 до 60 минут включительно
  - Требование 18 На главной странице должен отображаться рейтинг игроков по неделе/месяцу/всего
  - Требование 19 Пользователь должен иметь возможность просмотра повтора баттла
  - Требование 20 Пользователь должен иметь возможность кастомизации при создании лобби - сложность, задача, теги и временной лимит
  - Требование 21 Пользователь должен иметь возможность организовать турнир и создать турнирную сетку
  - Требование 22 После определения победителя пользоватеть должен иметь возможность остаться в баттле и дописать код / ознакомиться с кодом
  - Требование 23 Пользователь должен получать уведомления о начале баттла
  - Требоваеие 24 В таблице статистики завершенных игр пользователя должны отображаться иконки выиграл/проиграл/сдался
  - Требование 25 Пользователь должен иметь возможность писать сообщения в чате
  - Требование 26 Пользователь без регистрации должен иметь возможность провести ознакомительный баттл
non-functional:
  - Требование 27 Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Требование 28 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 29 Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Требование 30 Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Требование 31 Пользователь должен иметь возможность просматривать сайт как на английском, так и на русском языке
  - Требование 32 Пользователь должен иметь возможность удалить сообщение из чата
  - Требование 33 Пользователь должен иметь возможность выбрать фон редактора light или dark
  - Требование 34 Mинимальное время проведения баттла 3 минуты
  - Требование 35 Mаксимальное время проведения баттла 60 минут
  - Требование 36 Участник не может писать и изменять код соперника
  - Требование 37 Зрители не могут писать код и вносить изменения в код участников
  - Требование 38 Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Требование 39 Участники не могут вносить изменения в предустановленную задачу баттла
