---
functional:
  - Требование 1 Сайт должен иметь мобильную версию
  - Требование 2 Пользователь должен иметь возможность авторизации через Github
  - Требование 3 Пользователь должен иметь возможность авторизации и голосового чата через Discord
  - Требование 4 Кнопки "signin" и "signup" должны располагаться на титульной странице приложения и быть в поле видимости пользователя
  - Требование 5 Сайт должен быть доступен на различных устройствах
  - Требование 6 Пользователь должен иметь возможность просматривать истории батлов
  - Требование 7 Во время проведения баттла пользователь должен видеть текст задания и примеры
  - Требование 8 Во время проведения баттла пользователь должен иметь возможность писать решение задачи в редакторе приложения
  - Требование 9 Пользователь должен иметь возможность переподключиться к игре и продолжить баттл в случае, если соединение было прервано
  - Требование 10 
non-functional:
  - Требование 7 Веб-сайт должен быть разработан с учетом удобства использования
    и оптимизирован для скорости работы
  - Требование 8 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 9 Сайт должен быть протестирован на совместимость с последними
    версиями браузеров
  - Требование 10 Сайт 
  - Требование 12 Пользователь должен иметь возможность просматривать сайт как на английском, так и на русском языке
  - Требование 13 Пользователь должен иметь возможность удалить сообщение из чата
  - Требование 14 Кнопка  не должна закрывать текст 
  - Требование 15 После успешного 
  - Требование 16 При нажатии на кнопку  должно отображаться 
